### ISSUE TITLE
Page setup and routing

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#1]
## Value statement 
As a user
I need a navigation  
so that I can navigate between the pages "Dashboard", "Ausgaben", "Einnahmen" and "Profile"

## Description (Text, Scribble, Wireframe, Design)

<img width="738" alt="image" src="https://user-images.githubusercontent.com/79711003/197196876-393cffcf-ceea-40f4-9188-7520dba9b2c1.png">

## Acceptance criteria
- [x] the app has a navigation bar
- [x] there are 4 navelements in the navigation bar
- [x] on click of each of the navelements, the app leads me to the associated page
- [x] an active navelement is colored

## Tasks
- [x] create a navbar incl navelements
- [x] create 4 pages 
- [x] link the navelements with the pages
- [x] set an active prop, so that the navelements gets extra styling on actinve

## Size
small

**Comment by s-kond** [comment]
Ist gut nachvollziehbar und vom Umfang passend denke ich 👍
Eventuell müssten die Tasks noch kleinschrittiger formuliert werden?

**Comment by mpagels** [comment]
Looks good to me. Should not be the first story you should work on, because it has no value for the user, to switch to empty pages ;-) Just saying. Keep up the good work.
