### ISSUE TITLE
Expense page

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#2]
## Value statement
As a user
I need a page that shows every expense added to CommuniFI
so that I get a good overview of the users expenses

## Description 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/79711003/197199809-5f88293d-1557-44c6-b5b4-4a6a9f131181.png">

## Acceptance criteria
- [ ] the page "Ausgaben" shows every expense as a card
- [ ] the card carries the basic information number, description, amount, name and date of submit
- [ ] i can scroll down till the bottom of the page and see every card

## Tasks
- [ ] create a dummy database with example expenses
- [ ] create a card component
- [ ] map over the dummy database and create every card
- [ ] add some basic styling 

## Size
small

**Comment by mpagels** [comment]
Looks very good to me. Good work here.

Could be a good possibility to add a component test, that checks if every information is shown! ;-)
