### ISSUE TITLE
Loading animation

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#22]
## Value statement 
As a user
I need a loading animation when waiting on a page to load
so that i know the site is working and i just have to wait

## Description 
![image](https://user-images.githubusercontent.com/79711003/198993745-a394b316-2cbd-4f9e-a944-2059abd8c139.png)

## Acceptance criteria
- [ ] a loading animation appears on the expense page
- [ ] a loading animation appears on the expense detail page
- [ ] the loading animation vanishes when the data is loaded

## Tasks
- [ ] add an animation to expense page
- [ ] add an animation to expense detail page
- [ ] set expense detail page to swr render method

## Size
small
