### ISSUE TITLE
Search function for expenses/revenues

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#25]
## Value statement 
As a user 
I need a search bar 
so that i can search for expenses and revenues inside the app

## Description 

![image](https://user-images.githubusercontent.com/79711003/199300930-338ba604-b99f-4f79-b192-ad081dd89bac.png)
![image](https://user-images.githubusercontent.com/79711003/199301672-27af5443-8117-41fd-b847-34f96d37b868.png)
![image](https://user-images.githubusercontent.com/79711003/199302012-29b221fc-e1cb-4fa0-b651-481662f626dc.png)

## Acceptance criteria
- [ ] a search icons appears in the footer at expense and revenue page
- [ ] after clicking the search-bar, an input field appears. The App-Logo disappears and the subheader moves to the left
- [ ] putting text into the input field, results in the cards getting filtered
- [ ] even misspellings work
- [ ] the search functionallity searches the description, amount, receiptNumber and name field

## Tasks
- [ ] add a search icon to the header component
- [ ] render the search icon conditionally (just for paths "/ausgaben" and "/einnahmen")
- [ ] create a state each in expenses and revenues page, that holds the fetched db data and set the map function to that state
- [ ] create a searchbar component, which accepts an array an search attributes via props
- [ ] implement the searchbar component inside the revenues and expenses page. Pass the created state which holds the fetched db data and the search attributes, based on which site (expenses/revenues) you came from
- [ ] set the state (which you got via props) inside the search component using fuzzy search

## Size
large
