### ISSUE TITLE
Set status on expenses 

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#26]
## Value statement 
As a user
I need a status for the expenses
so that I can see which ones are payed and which ones are pending
## Description 
![image](https://user-images.githubusercontent.com/79711003/199307705-0b66dc00-b828-4b22-a1f4-0753336e9ec4.png)
![image](https://user-images.githubusercontent.com/79711003/199307836-187b3263-cdda-49ac-9491-672531c06ffd.png)
![image](https://user-images.githubusercontent.com/79711003/199309132-b0056e69-42b7-4d1c-9f71-1e79b1bccef6.png)

## Acceptance criteria
- [ ] the cards on the expense page  and the expense detail pages show the status of the expense
- [ ] there are two status: "Eingereicht" & "Bezahlt"
- [ ] "Bezahlt" gets set as initial value when adding an expense to the app
- [ ] In the edit form, you can switch the status 

## Tasks
- [ ] add a status field to the expenses schema and set it to "Eingereicht" on default
- [ ] add the status field into the api to process it
- [ ] render a status option in the expenseform, which is only rendered, when the status is not empty
- [ ] display the status on the card and the detailcard
- [ ] add a circly, which color depends on the status (via props)

## Size
medium
