### ISSUE TITLE
landing, login and registerpage

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#27]
## Value statement 
As a user
I need a landing, login and registerpage
so that I can start using the app and authentificate myself

## Description 
![image](https://user-images.githubusercontent.com/79711003/199310423-296f167a-96d9-4951-9ef9-6f321c04cd4b.png)
![image](https://user-images.githubusercontent.com/79711003/199310240-b588562b-d898-4cd1-8c19-87d809390e50.png)
![image](https://user-images.githubusercontent.com/79711003/199310268-98fec5fc-b23b-4edb-ba1a-9600f759482f.png)

## Acceptance criteria
- [ ] when i enter the app's domain, i access the landing page, holding a button that leads to the login page
- [ ] the login pages holds a button "login" which leads to the dashboard page (just a fake button by now, no real authentification)
- [ ] there is a register button as well, that leads to a register page
- [ ] A click on register also leads to the dashboard (no authentification)

## Tasks
- [ ] create landing page 
- [ ] create login page
- [ ] create register page
- [ ] link the pages which each user using next link

## Size
small
