### ISSUE TITLE
Expense detail page

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#3]
## Value statement 
As a user
I need a detail view of every expense
so that i can access every detail of the expense

## Description

<img width="317" alt="image" src="https://user-images.githubusercontent.com/79711003/197200800-32bb1af8-0106-4a2c-b662-cb638468d47f.png">

## Acceptance criteria
- [ ] A click on an expense on the "Ausgaben" page leads to a detail view of the expense 
- [ ] The detail view has a route like "../expense/[id]"
- [ ] The details are enclosed by a card looking similar to the cards of the expense page
- [ ] the card carries the basic information of the expense view and a picture of the receipt and a comment
- [ ] the data is generated via an API-Route + Services so that a database extension is easy to plug in

## Tasks
- [ ] create an [id].js page
- [ ] create a card-detail component
- [ ] create a service file an write a get request fed by the dummy data
- [ ] create an api route  using the service
- [ ] Link the expenseCards on the expense page with the api route over serversideprops

## Size
medium

**Comment by mpagels** [comment]
Awesome. Looks good to me.
