### ISSUE TITLE
Filter + sort function expenses/revenues

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#32]
## Value statement 
As a use
I need the possibility to sort and filter expenses/revenues
so that I get a better overview.

## Acceptance criteria
- [ ] the searchbar holds a filter icon
- [ ] after clicking the icon, a sidebar pops up
- [ ] the sidebar holds multiple options to sort and filter data
- [ ] after clicking the options, the results change immediately
- [ ] sortings and filter stack witch each other so that you can sort and filter at the same time

## Tasks
- [ ] create a filter component
- [ ] inside the filter component, render a sidebar with mutliple options to sort/filter
- [ ] write functions and connect them with the options of the ui
- [ ] inside the functions, manipulate the global filteredExpenses/filteredRevenues state, according to the labeling

## Size
 medium
