### ISSUE TITLE
Dashboard graphs

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#36]
## Value statement 
As a user
I need graphs on my dashboard page
so that i can u nderstand the fincancial situation of my team faster

## Acceptance criteria
- [ ] the dashboard page holds at least one graph
- [ ] the graph is connected to the data been visualized on the dashboard
- [ ] the graph is animated

## Tasks
- [ ] import a graph lib
- [ ] import a graph
- [ ] connect it with the data
- [ ] create the right data when needed 
-
## Size
 medium
