### ISSUE TITLE
Color scheme makeover

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#37]
## Value statement 
As a user
I need a pleasant color scheme
so that I can orientate myself in the app

## Acceptance criteria
- [ ] a global color scheme is set in globalStyles
- [ ] the color scheme is applied on every design component inside the app
- [ ] the color choice respect contrast ratios and accessibility critereia

## Tasks
- [ ] choose color scheme
- [ ] set color scheme in globalstyle
- [ ] apply the color scheme in every component

## Size
medium
