### ISSUE TITLE
Expense add function

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#4]
## Value statement - a requirement, not a solution
As a user
I need an add button in expenses, that leads to an add form
so that i can add my expense to the expense page.

## Description 

<img width="309" alt="image" src="https://user-images.githubusercontent.com/79711003/197017581-f1d860ab-bc26-4606-bb3b-b16aaec3e549.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/79711003/197017644-d0696440-66fe-45dd-8e61-febc555c7b51.png">

## Acceptance criteria
- [ ] an add button on the expense page leads to an expense form
- [ ] in the expense form i can insert my expense data (the image upload is not included by now - just leave it out)
- [ ] the description and amount ("Beschreibung" und "Betrag") are required inputs. Beschreibung ist type text, "Betrag" is type number 
- [ ] the submit button in the expense form adds the data to the expense list
- [ ] after the submit I get redirected to the expense list, with my commited expense at top
- [ ] the edit button is blue during the whole time but when the user clicks on it before every required field is filled out, he/she gets a notification  (greyed out version comes with ux stories later on)

## Tasks
- [ ] add an add-button on the expenses page
- [ ] create expense create page
- [ ] link add button with the expense create page
- [ ] create an form component for the create page
- [ ] write a service that handles the submit and adds it to the expenselist
- [ ] expand the api-route for the expenses with a post request
- [ ] link the handle-service with the api endpoint (for later DB-connection)

## Size
medium

**Comment by Kheirah** [comment]
Good start!
Consider adding the image upload in a later separate user story. As a user when I see an image upload, I'd expect that it works, wouldn't I? The story of adding an expense would work without adding/uploading an image. Hence, I'd higly recommend to add the feature later on. As a general rule of thumb, never add anything that doesn't yet work for the user.

Further points highly worth considering:
- Which fields are required? Could I save an expense without a description? How do you inform the user about the missing required info?
- What type is your "amount" field (number, text)? And what happens when, say, it's a text and I enter "five hundred"?
- What happens if I enter a negative value in the amount field?
- How does the submit button behave throughout the form submission? Is it disabled (grayed out) as long as the necessary information is still missing? Does it become active when all required info has been gathered? What happens when the user clicks the button at any point in time?
