### ISSUE TITLE
Authentification 

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#41]
## Value statement 
As a user
I need the possibility to login with my existing github login
so that dont need a registration

## Description 

![image](https://user-images.githubusercontent.com/79711003/201334411-1f6bbe80-627c-4016-adda-e11a19a16d25.png)

## Acceptance criteria
- [ ] the login page holds a "sign in with GitHub" button
- [ ] by clicking the button, you get redirected to the login page

## Tasks
- [ ] create a github login button
- [ ] install nextAuth
- [ ] install github provider 
- [ ] connect login button with nextauth

## Size
medium
