### ISSUE TITLE
Profil page

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#43]
## Value statement 
As a user
I need a profile page
so that I can view my profile data and log out if i want to

## Description 
![image](https://user-images.githubusercontent.com/79711003/201686175-83c31354-9e6b-449e-8daf-49bbafb2d54c.png)

## Acceptance criteria
- [ ] after logging in, the profile page is accessible via navbar
- [ ] the page shows the username 
- [ ] the page has a logout button
- [ ] after loggin out, you get redirected to the login page

## Tasks
- [ ] create a profile page
- [ ] add it to the navbar
- [ ] show the session info on the page
- [ ] add a logout button

## Size
small
