### ISSUE TITLE
Protected Routes

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#45]
## Value statement 
As an administratior
I need protected routes
so that users can only access the app, when they log in

## Acceptance criteria
- [ ] if you call a route, that should be protected (e.g. /dashboard) and are not logged in --> you get redirected to login page

## Tasks
- [ ] create protected routes
- [ ] check session 
- [ ] add callback to login page 

## Size
small
