### ISSUE TITLE
User database

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#47]
## Value statement 
As a admin
I need a database for users
so that users and sessions get saved over time

## Acceptance criteria
- [ ] sessions and unseres are saved in mongo db

## Tasks
- [ ] add mongo adapter to next auth
- [ ] write user scheme

## Size
small
