### ISSUE TITLE
Additional profile data

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#49]
## Value statement 
As a user
I need additional infos on my profile
so that I can select a name, my current address and my IBAN

## Acceptance criteria
- [ ] the profile holds the additional fields: town, street, name and IBAN
- [ ] the infos are editable via a edit button
- [ ] after clicking save, the data gets updated in the database

## Tasks
- [ ] add the additional data fields on the profile-page
- [ ] create an edit page for the profile
- [ ] add a service and a request method in the api, to handle the edit data

## Size
small
