### ISSUE TITLE
Expense edit function

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#5]
## Value statement - a requirement, not a solution
As a user
I need an edit function for every expense
so that I can edit the expense when needed

## Description (Text, Scribble, Wireframe, Design)
<img width="331" alt="image" src="https://user-images.githubusercontent.com/79711003/197206482-d2263265-4c89-46cc-b24f-f39f0e014ea4.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/79711003/197206588-d6028b0a-7852-4eea-a4ca-59039a216e40.png">

## Acceptance criteria
- [ ] the expense detail page holds an edit button
- [ ] on click, the edit button leads to the expense form
- [ ] the expense form is filled with the data of the expense on which i clicked the expense button
- [ ] the data in the form is editable (not the image by now!)
- [ ] after clicking the submit button, i get redirected to the detail view of the expense
- [ ] the detail information of the expense matches with the input data i editet in the form

## Tasks
- [ ] create an edit button on the detail expense page
- [ ] create an edit page for the expenses including the expense form component
- [ ] link the edit button with the edit page
- [ ] edit the expense form, so that i manages the values via multiple states
- [ ] connect the values of the inputs with the states
- [ ] create an additional PUT method in the api route, that manages the edit request
- [ ] connect the submit button with the api route

## Size
medium

**Comment by mpagels** [comment]
looks good to me.
