### ISSUE TITLE
Username in expenses and revenues

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#51]
## Value statement 
As a user
I need my name automatically added to revenues and expenses I create
so that everyone knows their origin.

## Description 
![image](https://user-images.githubusercontent.com/79711003/202393132-344beee2-1389-41f7-9e9a-f3938946b6a9.png)

## Acceptance criteria
- [ ] after adding a a revenue or expense, the name of its creator is being added to it
- [ ] the name is visible on expense/revenue and detail page
- [ ] the name cant be changed by edit
- [ ] the name is referenced (populated) by the users the id, so that it changes when the according user renames itself

## Tasks
- [ ] change the expenseService and  the revenueService so that it adds the user id when adding an expense or revenue
- [ ] populate the users name 

## Size
medium
