### ISSUE TITLE
User detail page

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#54]
## Value statement 
As a user
I need a user detail page which can be accessed in the detail views of expenses/revenues
so that I can get more information of the creator of the expense/revenue

## Description 
![image](https://user-images.githubusercontent.com/79711003/202464386-75a26ec0-5b13-4a9c-87bf-e505880928ef.png)
![image](https://user-images.githubusercontent.com/79711003/202477698-ea64e268-26fc-414c-988b-a2451a90ddaf.png)

## Acceptance criteria
- [ ] by clicking the name on the detail page of expense/revenue i get redirected to the profile page of the creator
- [ ] the profile page looks similar to "/profile"
- [ ] a back button brings me back to the card details

## Tasks
- [ ] add a link to the name
- [ ] call the dynamic profile id page onclick
- [ ] add a back button, that redirects you to the card details

## Size
small

**Comment by MeenaFoerderer** [comment]
Looks good. However, I would suggest you also display the back button that you want to create in your profile page design.
