### ISSUE TITLE
Revenues page and functions

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#6]
## Value statement - a requirement, not a solution
As a user 
I need the opportunity to view, add and edit revenues
so that I can keep track of the revenues of my team

## Description 
This story seams to be large but its basically copy paste of issues edanum/capstone-communifi#2 edanum/capstone-communifi#3  edanum/capstone-communifi#4  and edanum/capstone-communifi#5 . There is no need to make smaller stories, because the accecptance criteria of the functions were met before. 

View

<img width="266" alt="image" src="https://user-images.githubusercontent.com/79711003/197210716-4bdc5995-94d8-4a68-a7ac-b3743deb4d66.png">

Detail View

<img width="253" alt="image" src="https://user-images.githubusercontent.com/79711003/197210817-1f92152d-1be8-4901-9357-7a69d0e13fb4.png">

Add

<img width="283" alt="image" src="https://user-images.githubusercontent.com/79711003/197210863-e774c2d5-0266-4bf7-a8a3-112993808d4b.png">

Edit

<img width="262" alt="image" src="https://user-images.githubusercontent.com/79711003/197210923-586db2eb-01ec-49ad-89af-17da24cb649e.png">

## Acceptance criteria
- [ ] By clicking on "Einnahmen" in the navbar, I get an overview of every expense of the team (analogue to edanum/capstone-communifi#2 )
- [ ] By clicking on a revenue Card, I can access a detail view of the revenue (analogue to edanum/capstone-communifi#3 )
- [ ] By clicking on the add button on the revenues page, i access an add_renvenue form and can add new revenues to the revenues list (analogue to edanum/capstone-communifi#4 )
- [ ] By clicking on the "Edit Button" at the revenue detail page, I can edit the revenue and save it (analogue to edanum/capstone-communifi#5 )

## Tasks
- [ ] Copy paste the folder [pages/expenses] and rename the folder to "revenues"
- [ ] Update all copied files by renaming "Ausgaben" to "Einnahmen" and 
- [ ] Create a new local dummy database with the name "revenues"
- [ ] Copy paste the expenseServices file in the services directory and update all names and imports to revenues
- [ ] Copy paste the api routes of expenses and  rename + update all name and import to revenues and link the new local database "expenses"

## Size
medium

**Comment by dorosiemers** [comment]
Ist das schon ein Fall von don't repeat yourself? (Ernstgemeinte Frage!)

**Comment by edanum** [comment]
Das ist wirklich eine gute Frage. Es ist mit Sicherheit möglich die Redundanz rauszubringen aber mir ist es grad noch ein wenig zu Heikel das zusammenzubringen. Denke ich nochmal drüber nach, danke für die Anmerkung :)
