### ISSUE TITLE
Dynamic Header information

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#7]
## Value statement
As a user
I need dynamic header information
so that I know on which page I'm at an can access a "back" button when needed

## Description

View on main pages

![image](https://user-images.githubusercontent.com/79711003/197219429-bb50fc90-baa5-4592-9fb5-e91593cbd79f.png)

View von subpages

<img width="404" alt="image" src="https://user-images.githubusercontent.com/79711003/197219595-bc20b7c1-dbe0-4ae4-8f49-ee6defd10ea7.png">

<img width="322" alt="image" src="https://user-images.githubusercontent.com/79711003/197219694-51e6901b-0522-4c8a-8921-61c4c6ac1fc5.png">

## Acceptance criteria
- the main pages show the logo + pagename
- every subpage shows a back button, which leads me to the page i came from to access the subpage
- the information is generated dynamically in the header component

## Tasks
- [ ] write a function in the header component, that generates a subtitle based on the pathnahme
- [ ] create a back button that leads to the last viewed page
- [ ] add the rendering of the button to the created function
- [ ] call the function in the header component return

## Size
small
