### ISSUE TITLE
Dashboard view

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#8]
## Value statement 
As a user
I need an dashboard view
so that I get an overview of expenses and revenues (related to each other) of the team 

## Description 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/79711003/197222709-1788a540-02e8-4cf7-b8b7-a4ce11353de0.png">

## Acceptance criteria
- The dashboard shows one card with the title "Gewinn&Verlust"
- The card holds three main values: 
  - sum of all expenses
  - sum of all revenues
  - the result of revenues - expenses 
- just basic styling! (without the bars showed in the screenshot)

## Tasks
- [ ] create the three values in the dashboard page and 
- [ ] import the data of expenses and revenues using the existing api routes
- [ ] show the result

## Size
medium
