### ISSUE TITLE
Set up Database

### ISSUE THREAD

**Issue by edanum** [edanum/capstone-communifi#9]
## Value statement - a requirement, not a solution
As a user
I need my data to be saved on a database
so that i can access it from anywhere without being stuck on a local device.

## Description 

Implement a backend! The data should be saved on a database, instead of localStorage.

## Acceptance criteria
- [ ] every data in communiFI is saved in a MongoDB
- [ ] every data in communiFI is read out of a MongoDB
- [ ] the data is seperated into multiple clusters (one cluster for expenses, one for revenues and so on)

## Tasks
- [ ] create a Cluster in MongoDB
- [ ] create multiple collections in MongoDB
- [ ] create schema with mongoose for the different collections
- [ ] write a connectodb function in your project
- [ ] dock mongo to the services and api endpoints 

## Size
medium
